'use strict';
const $=selector=>document.querySelector(selector);
const INFO={
 normal:{name:'Normal cache',title:'One answer. <em>Reused exactly.</em>',description:'Send the same stable question to fresh generation and an exact response cache in Oracle. Writes go to the primary database; reads are served by Oracle True Cache, which follows the primary with no invalidation code.',hint:'Stores a complete answer for the same sandbox, model, source context and exact request. Reads try True Cache, then the primary if True Cache has not caught up. TTL limits its lifetime.',query:'Explain why an exact response cache needs a TTL.',alternative:'Explain why an exact response cache needs a namespace.'},
 embedding:{name:'Embedding cache',title:'Encode once. <em>Recall the vector.</em>',description:'Compare a local open-source encoder run (all-MiniLM-L6-v2 from Hugging Face) with a cached vector. The complete 384-dimensional vectors and encoder token counts appear below.',hint:'Reuses a vector for identical text, model, revision, input role and dimensions. It avoids encoder compute, rather than LLM generation. MiniLM has no role prompt, so both roles produce the same vector under separate keys.',query:'A semantic cache retrieves previously generated answers.',alternative:'An embedding cache avoids repeated encoder requests.'},
 semantic:{name:'Semantic cache',title:'A familiar intent. <em>A recalled answer.</em>',description:'Compare fresh generation with an Oracle HNSW cache built from raw vector SQL. Inspect the matched question and distance before trusting reuse.',hint:'Oracle compares question vectors within this sandbox and source revision. A candidate must pass the distance threshold, then a local cross-encoder reranker must confirm the match. TTL limits reuse.',query:'Explain how semantic caching helps agent memory.',alternative:'How can a semantic cache help an agent reuse an earlier answer?'},
 prompt:{name:'Prompt cache',title:'Stable context. <em>Fresh answers.</em>',description:'Claude still generates on both sides. Its API reports the input tokens read from cache, newly written and processed uncached.',hint:'An explicit Anthropic breakpoint caches the stable reference prefix. The changing question follows it. Writes and output still cost money.',query:'Explain embedding caching in two sentences.',alternative:'How does HNSW retrieval help agent memory?'},
 tool:{name:'Tool cache',title:'Live evidence. <em>Briefly remembered.</em>',description:'Run the same Tavily search through fresh and cached tool paths. Both sides ask Claude to answer from the results.',hint:'Reuses a read-only Tavily response with identical search arguments. It preserves the original collection time and uses a short TTL.',query:'Oracle AI Database HNSW vector search official documentation',alternative:'TAP Air Portugal official cabin baggage allowance'},
 unified:{name:'Unified stack',title:'Five layers. <em>One measured path.</em>',description:'Compare an uncached retrieval pipeline with your chosen cache stack. OracleSemanticCache supplies semantic reuse in this combined interface.',hint:'Exact answer (True Cache) → semantic answer (HNSW + reranker check) → evidence retrieval (HNSW + reranker) or live tool → prompt caching → fresh Claude output. Each layer saves a different kind of work.',query:'Explain how semantic caching helps agent memory.',alternative:'How can an agent reuse a previous answer through a semantic cache?'}
};
const FEATURE_INFO={normal:['Exact answer cache',INFO.normal.hint],embedding:['Embedding cache',INFO.embedding.hint],semantic:['Semantic answer cache',INFO.semantic.hint],prompt:['Provider prompt caching',INFO.prompt.hint],tool:['Tavily tool cache',INFO.tool.hint]};
let health={ready:false},version=0,cleanup=null,pending=false,lastComparison=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usd=v=>v===null||v===undefined?'Unknown':'$'+Number(v).toFixed(6);
const secs=v=>Number(v).toFixed(3)+' s';
const when=v=>new Date(v*1000).toLocaleString();
async function api(path,payload){const response=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,6000);}
async function busy(button,fn){if(!health.ready){toast(health.error||'Providers and Oracle are warming up.');return;}if(pending){toast('A provider request is still running.');return;}pending=true;button.disabled=true;const text=button.textContent;button.textContent='Working…';try{await fn();}catch(e){toast(e.message);}finally{pending=false;if(button.isConnected){button.disabled=button.dataset.keepDisabled==='true';button.textContent=text;}}}
function richText(value){let text=esc(value).replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>');return text.split(/\n\s*\n/).map(p=>p.startsWith('#')?'<h3>'+p.replace(/^#+\s*/,'')+'</h3>':'<p>'+p.replace(/\n/g,'<br>')+'</p>').join('');}
function hero(eyebrow,title,description){return `<div class="hero"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div>`;}
function featureControls(prefix,features=null){const saved=features||JSON.parse(localStorage.getItem('cache-features')||'{"normal":true,"embedding":true,"semantic":true,"prompt":true,"tool":true}');return `<div class="option-grid">${Object.entries(FEATURE_INFO).map(([key,[name,hint]])=>`<label class="option-hint"><span><input type="checkbox" data-feature="${key}" name="${prefix}" ${saved[key]?'checked':''}>${name}</span><small>${hint}</small></label>`).join('')}</div>`;}
function readFeatures(root){return Object.fromEntries([...root.querySelectorAll('[data-feature]')].map(n=>[n.dataset.feature,n.checked]));}
function configControls(prefix='compare'){return `<details class="cache-settings"><summary>Cache identity, lifetime and search settings</summary><div class="cache-controls"><div><label for="${prefix}-revision">Source / context revision</label><input id="${prefix}-revision" value="v1" maxlength="80"><small class="hint">Changing this invalidates the answer namespace and stable prompt.</small></div><div><label for="${prefix}-ttl">Answer / embedding TTL · seconds</label><input id="${prefix}-ttl" type="number" value="300" min="0.1" max="3600" step="0.1"></div><div><label for="${prefix}-tool-ttl">Tool TTL · seconds</label><input id="${prefix}-tool-ttl" type="number" value="60" min="0.1" max="300" step="0.1"></div><div><label for="${prefix}-threshold">Maximum cosine distance</label><input id="${prefix}-threshold" type="number" value="0.10" min="0" max="0.6" step="0.01"><small class="hint">Lower distance is a closer match; a larger threshold admits more candidates. A reranker check still has to confirm each candidate.</small></div><div><label for="${prefix}-depth">Tavily search depth</label><select id="${prefix}-depth"><option value="basic">Basic</option><option value="advanced">Advanced · higher credit cost</option></select></div><div><label for="${prefix}-max-results">Search result limit</label><input id="${prefix}-max-results" type="number" value="3" min="1" max="5"></div></div></details>`;}
function readConfig(prefix='compare',features=null){return {revision:$('#'+prefix+'-revision').value,ttl:Number($('#'+prefix+'-ttl').value),tool_ttl:Number($('#'+prefix+'-tool-ttl').value),threshold:Number($('#'+prefix+'-threshold').value),depth:$('#'+prefix+'-depth').value,max_results:Number($('#'+prefix+'-max-results').value),features:features||{normal:true,embedding:true,semantic:true,prompt:true,tool:true}};}
function tokens(metrics){const total=metrics.processed_input_tokens||1;return `<div class="tokens-bar" aria-label="Actual provider input tokens"><span class="input" style="width:${metrics.input_tokens/total*100}%"></span><span class="write" style="width:${metrics.cache_write_tokens/total*100}%"></span><span class="read" style="width:${metrics.cache_read_tokens/total*100}%"></span></div><div class="token-key"><span>Uncached ${metrics.input_tokens}</span><span>Write ${metrics.cache_write_tokens}</span><span>Read ${metrics.cache_read_tokens}</span><span>Output ${metrics.output_tokens}</span></div>`;}
function metricsHTML(m){return `<div class="mini-metrics"><div><small>Latency</small><b>${secs(m.seconds)}</b></div><div><small>Estimated API cost</small><b>${usd(m.estimated_usd)}</b></div><div><small>LLM calls</small><b>${m.provider_calls}</b></div><div><small>Embedding calls / tokens</small><b>${m.embedding_calls} / ${m.embedding_tokens}</b></div><div><small>Search calls</small><b>${m.tool_calls}</b></div><div><small>Cached input tokens</small><b>${m.cache_read_tokens}</b></div></div>${tokens(m)}`;}
function heatmap(canvas,vector,h=160){const dpr=devicePixelRatio||1,w=canvas.clientWidth||300,cols=32,rows=Math.ceil(vector.length/cols);canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const max=Math.max(.001,...vector.map(Math.abs));vector.forEach((v,i)=>{ctx.fillStyle=v>=0?`rgba(82,226,189,${.2+.8*v/max})`:`rgba(173,155,255,${.2-.8*v/max})`;ctx.fillRect(i%cols*w/cols,Math.floor(i/cols)*h/rows,w/cols-1,h/rows-1);});canvas.onmousemove=e=>{const box=canvas.getBoundingClientRect(),index=Math.min(vector.length-1,Math.floor((e.clientY-box.top)/box.height*rows)*cols+Math.floor((e.clientX-box.left)/box.width*cols));canvas.title='Dimension '+(index+1)+': '+vector[index].toFixed(6);};}
function pane(row,side,mechanism){const hit=row.hit?(row.cache_hits||[row.hit]).join(' + ').toUpperCase()+' HIT':'MISS · FRESH WORK';const evidence=(row.evidence||[]).filter(v=>typeof v==='object');return `<div class="panel-head"><h2>${side==='without'?'WITHOUT CACHE':'WITH '+INFO[mechanism].name.toUpperCase()}</h2><span class="pill cache-badge ${row.hit?'hit':''}">${hit}</span></div><div class="result-body">${row.status==='failure'?`<div class="error-banner">${esc(row.error)}</div>`:`<span class="eyebrow">YOUR REQUEST</span><p>${esc(row.query)}</p>${row.vector?`<canvas class="vector-grid" id="vector-${side}"></canvas><p>${row.dimensions.toLocaleString()} dimensions · norm ${row.norm.toFixed(6)}<br><small class="hint">Vector fingerprint ${row.fingerprint.slice(0,16)}</small></p>`:`<span class="eyebrow">CLAUDE</span>${richText(row.answer||'')}`}${row.distance!==undefined&&row.distance!==null?`<div class="memory-preview"><b>Closest question · distance ${row.distance.toFixed(5)}${typeof row.rerank_score==='number'?' · reranker score '+row.rerank_score.toFixed(2):''}</b><p>${esc(row.matched_question)}</p></div>`:''}${row.collected_at?`<p class="hint">Evidence collected ${when(row.collected_at)} · age ${Math.max(0,Math.round(Date.now()/1000-row.collected_at))} s</p>`:''}${evidence.length?`<details><summary>${evidence.length} live sources</summary>${evidence.map(item=>`<div class="source-item"><a href="${esc(/^https?:\/\//.test(item.url)?item.url:'#')}" target="_blank" rel="noopener">${esc(item.title||item.url)}</a><p>${esc((item.content||'').slice(0,450))}</p></div>`).join('')}</details>`:''}<ol class="cache-trace">${(row.trace||[]).map(item=>`<li>${esc(item.step)} · <b>${esc(item.outcome)}</b></li>`).join('')}</ol>`}</div><div class="result-metrics">${metricsHTML(row.metrics)}</div>`;}
function showComparison(result,ticket){if(ticket!==version)return;lastComparison=result;refreshExplorer();for(const side of ['without','with']){const node=$('#pane-'+side);if(!node)return;node.innerHTML=pane(result[side],side,result.mechanism);if(result[side].vector)heatmap($('#vector-'+side),result[side].vector);}
 $('#comparison-status').textContent='Measured execution · '+result.namespace.slice(0,12)+' · '+(result.with.hit?'A real cache hit was observed.':result.with.reuse_eligible===false&&result.with.reuse_reason&&['normal','semantic','unified'].includes(result.mechanism)?'No answer reuse for this request: '+result.with.reuse_reason+'.':'No cache hit yet. Repeat the request or inspect the match.')+(['semantic','unified'].includes(result.mechanism)?' Maximum accepted cosine distance: '+result.threshold+'.':'');
 $('#comparison-extra').innerHTML=`<section class="panel delta-panel"><div><small>Signed latency saving for this pair</small><br><strong>${secs(result.savings.seconds)}</strong></div><div><small>Signed API cost saving</small><br><strong>${usd(result.savings.estimated_usd)}</strong></div><small>Negative values mean this cached request was slower or cost more.<br>Lane setup: ${secs(result.setup.seconds)} · ${usd(result.setup.estimated_usd)} (separate).</small></section>${result.prefix?`<details class="prefix-window"><summary>Inspect the stable prefix before Claude’s cache breakpoint</summary><div class="prompt-text">${esc(result.prefix)}</div><p class="hint">Dynamic suffix: this request and its selected evidence. Cache reads still produce new output.</p></details>`:''}`;
}
async function comparison(mechanism,ticket){const info=INFO[mechanism];$('#stage').innerHTML=hero('CACHE '+String(Object.keys(INFO).indexOf(mechanism)+1).padStart(2,'0'),info.title,info.description)+`<section class="panel"><div class="panel-body"><label for="shared-query">One input for both paths</label><textarea id="shared-query">${esc(info.query)}</textarea><div class="cache-controls">${mechanism==='embedding'?'<div><label for="embedding-role">Embedding input role</label><select id="embedding-role"><option value="">Shared role</option><option value="query">Query</option><option value="document">Document</option></select></div>':mechanism==='tool'?'':`<div><label for="request-kind">Request type</label><select id="request-kind"><option value="explanation">Stable educational question</option><option value="live">Live web research · fresh answers</option></select>${['normal','semantic'].includes(mechanism)?`<small class="hint" id="kind-note" hidden>Live research is never answered from the ${info.name.toLowerCase()}: current facts are fetched fresh every time, so this lane always misses. Choose Stable educational question to see a hit.</small>`:''}</div>`}</div>${mechanism==='unified'?`<div id="stack-options">${featureControls('stack-feature')}</div>`:''}${configControls()}<div class="query-actions"><button class="button" id="compare">Send to both ↗</button><button class="button secondary" id="repeat">Repeat request</button><button class="button secondary" id="alternative">${mechanism==='semantic'?'Try a paraphrase':'Try another input'}</button><button class="button secondary" id="reset-cache">Start cold</button></div><p class="hint">${info.hint}</p><div class="comparison-status" id="comparison-status">The first cached request may still do all the work.</div></div></section><div class="comparison-grid"><section class="panel" id="pane-without"><div class="panel-head"><h2>Without cache</h2><span class="pill">A</span></div><div class="result-body hint">Send an input to run the baseline.</div></section><section class="panel" id="pane-with"><div class="panel-head"><h2>With ${info.name.toLowerCase()}</h2><span class="pill">B</span></div><div class="result-body hint">Measured cache decisions appear here.</div></section></div><div id="comparison-extra"></div>${mechanism==='semantic'?'<div id="vector-space"></div>':''}`;
 const send=button=>busy(button,async()=>{const query=$('#shared-query').value.trim();if(!query)throw new Error('Enter an input.');const payload={query,kind:$('#request-kind')?.value||'explanation',role:$('#embedding-role')?.value||null,config:readConfig('compare',mechanism==='unified'?readFeatures($('#stack-options')):null)};$('#comparison-status').textContent='Running real provider requests…';showComparison(await api('/api/compare/'+mechanism,payload),ticket);});
 $('#compare').onclick=()=>send($('#compare'));$('#repeat').onclick=()=>send($('#repeat'));$('#alternative').onclick=()=>$('#shared-query').value=info.alternative;
 $('#reset-cache').onclick=()=>busy($('#reset-cache'),async()=>{await api('/api/reset/'+mechanism,{});if(ticket!==version)return;$('#comparison-status').textContent=mechanism==='prompt'?'New prefix identity selected. Its next provider call can write a fresh cache.':'A fresh cache namespace is ready.';lastComparison=null;$('#comparison-extra').innerHTML='';for(const side of ['without','with'])$('#pane-'+side).innerHTML='<div class="panel-body hint">New namespace. Send a request to measure the cold path.</div>';});
 const kindNote=()=>{if($('#kind-note'))$('#kind-note').hidden=$('#request-kind').value!=='live';};if($('#request-kind'))$('#request-kind').addEventListener('change',kindNote);
 if(mechanism==='unified')$('#stack-options').onchange=()=>localStorage.setItem('cache-features',JSON.stringify(readFeatures($('#stack-options'))));
 try{const history=await api('/api/history/'+mechanism);if(ticket!==version)return;if(history.length){const previous=history.at(-1);$('#shared-query').value=previous.without.query;if(previous.config){for(const key of ['revision','ttl','tool_ttl','threshold','depth','max_results']){const node=$('#compare-'+key.replaceAll('_','-'));if(node)node.value=previous.config[key];}if(mechanism==='unified')$('#stack-options').innerHTML=featureControls('stack-feature',previous.config.features);}if($('#request-kind')){$('#request-kind').value=previous.kind;kindNote();}if($('#embedding-role'))$('#embedding-role').value=previous.role||'';showComparison(previous,ticket);}}catch(e){if(ticket===version&&health.ready)toast(e.message);}
 // Start the vector-space viewer after the history restore, so its request cannot delay restoring the settings.
 if(mechanism==='semantic'&&ticket===version)renderVectorSpace(ticket);
}
function overview(){const setup=health.shared_setup?.metrics;$('#stage').innerHTML=hero('CACHE TECHNIQUES · IN ACTION','Do less work. <em>Measure every layer.</em>','Use the same input on two paths, watch the actual cache decisions, and compare latency, tokens and API cost. Then combine the layers in a shared workload.')+`<div class="hero-badges"><span class="pill good">Oracle AI Database · HNSW</span><span class="pill">Raw Claude Opus 5.5</span><span class="pill">Local MiniLM · 384D + reranker</span><span class="pill">Oracle True Cache</span><span class="pill">Tavily live search</span></div><div class="tech-grid">${Object.entries(INFO).map(([key,item],i)=>`<a class="panel tech-card" href="#cache/${key}"><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h2>${item.name}</h2><p>${item.hint}</p><span class="pill">Compare both paths ↗</span></a>`).join('')}</div><section class="panel"><div class="panel-body overview-oracle"><div><span class="eyebrow">SHARED ORACLE CORPUS</span><p>Eight authored passages, one coherent vector space.</p></div><div><b>${setup?usd(setup.estimated_usd):'Warming'}</b><p class="hint">Observed shared startup cost · separate from lane costs</p></div><div class="actions"><a class="button" href="#tokenomics">Run the Tokenomics lab ↗</a><a class="button secondary" href="#architecture">Explore the architecture</a></div></div></section><p class="hint">API estimates include reported Claude tokens and Tavily credits. Embeddings and reranking run locally (no API cost); local database/CPU costs and account discounts are excluded. No answer-quality score is inferred from lower cost.</p>`;}
function route(){if(cleanup){cleanup();cleanup=null;}const ticket=++version,hash=location.hash.slice(1)||'overview';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.getAttribute('href')==='#'+hash));$('#sidebar').classList.remove('open');if(hash.startsWith('cache/')&&INFO[hash.slice(6)])comparison(hash.slice(6),ticket);else if(hash==='tokenomics')renderTokenomics(ticket);else if(hash==='architecture')renderArchitecture(ticket);else overview();}
async function poll(){try{const was=health.ready;health=await api('/api/status');$('#provider-status').textContent=health.ready?'Oracle · connected':'Providers · warming';$('#price-date').textContent=health.pricing_date;$('#new-sandbox').disabled=!health.ready;if(health.error)toast(health.error);if(health.ready&&!was)route();}catch(e){$('#provider-status').textContent='Server unavailable';}if(!health.ready)setTimeout(poll,1500);}
$('#chapters').innerHTML=Object.entries(INFO).map(([key,item],i)=>`<a class="nav" href="#cache/${key}"><span class="nav-number">${String(i+1).padStart(2,'0')}</span>${item.name}</a>`).join('');
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#theme').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';$('#new-sandbox').onclick=()=>busy($('#new-sandbox'),async()=>{const result=await api('/api/sandbox',{});health.workspace=result.workspace;localStorage.removeItem('cache-job');route();toast('New sandbox: all application cache namespaces start empty.');});window.addEventListener('hashchange',route);window.addEventListener('DOMContentLoaded',()=>{route();poll();});
